% LEXICON

% NOUNS
% ======

% Proper Names
% ------------

fido ---> (word,
           phon:[(a_ fido)],
	   synsem:loc:(cat:head:(noun,
                                  pred:minus),
                      cont:(npro,
		            index:(Index,
				  ref,
                                  pers:third),
			    restr:[]),
		      context:background:[(naming_rel,
					   bearer:Index,
					   name:fido),
					  (non_aggregate_rel,
					   inst:Index),
					  (non_human_rel,
					   inst:Index)]),
	   qstore:[],
	   retr:[],
           arg_st:e_list).

john  ---> (word,
           phon:[(a_ john)],
	   synsem:loc:(cat:head:(noun,
                                  pred:minus),
                      cont:(npro,
		            index:(Index,
				  ref,
                                  pers:third),
			    restr:[]),
		      context:background:[(naming_rel,
					   bearer:Index,
					   name:john),
					  (non_aggregate_rel,
					   inst:Index),
					  (male_rel,
					   inst:Index)]),
	   qstore:[],
	   retr:[],
           arg_st:e_list).

kim  ---> (word,
           phon:[(a_ kim)],
	   synsem:loc:(cat:head:(noun,
                                  pred:minus),
                      cont:(npro,
		            index:(Index,
				  ref,
                                  pers:third),
			    restr:[]),
		      context:background:[(naming_rel,
					   bearer:Index,
					   name:kim),
					  (non_aggregate_rel,
					   inst:Index),
					  (human_rel,
					   inst:Index)]),
	   qstore:[],
	   retr:[],
           arg_st:e_list).


mary ---> (word,
           phon:[(a_ mary)],
	   synsem:loc:(cat:head:(noun,
                                  pred:minus),
                      cont:(npro,
		            index:(Index,
				   ref,
                                  pers:third),
			    restr:[]),
		      context:background:[(naming_rel,
					   bearer:Index,
					   name:mary),
					  (non_aggregate_rel,
					   inst:Index),
					  (female_rel,
					   inst:Index)]),
	   qstore:[],
	   retr:[],
           arg_st:e_list).


peter ---> (word,
            phon:[(a_ peter)],
	    synsem:loc:(cat:head:(noun,
                                  pred:minus),
                        cont:(npro,
			      index:(Index,
				     ref,
                                    pers:third),
			      restr:[]),
			context:background:[(naming_rel,
					     bearer:Index,
					     name:peter),
					  (non_aggregate_rel,
					   inst:Index),
					  (male_rel,
					   inst:Index)]),
	    qstore:[],
	    retr:[],
            arg_st:e_list).

sandy  ---> (word,
           phon:[(a_ sandy)],
	   synsem:loc:(cat:head:(noun,
                                  pred:minus),
                      cont:(npro,
		            index:(Index,
				   ref,
                                  pers:third),
			    restr:[]),
		      context:background:[(naming_rel,
					   bearer:Index,
					   name:sandy),
					  (non_aggregate_rel,
					   inst:Index),
					  (human_rel,
					   inst:Index)]),
	   qstore:[],
	   retr:[],
           arg_st:e_list).


% Pronouns

he ---> (word,
         phon:[(a_ he)],
	 synsem:loc:(cat:head:(noun,
                              case:nom,
                              pred:minus),
                     cont:(ppro,
		           index:(Index,
				  ref,
                                  num:sg,
                                  pers:third),
			   restr:[]),
		     context:background:[(male_rel,
					  inst:Index)]),
	qstore:[],
	retr:[],
        arg_st:e_list).

she ---> (word,
          phon:[(a_ she)],
	  synsem:loc:(cat:head:(noun,
                                case:nom,
                                pred:minus),
                     cont:(ppro,
		           index:(Index,
				  ref,
                                 num:sg,
                                 pers:third),
			   restr:[]),
		     context:background:[(female_rel,
					  inst:Index)]),
	qstore:[],
	retr:[],
        arg_st:e_list).

it ---> (word,
         phon:[(a_ it)],
	 synsem:loc:(cat:head:(noun,
                               pred:minus),
                    cont:(ppro,
		          index:(Index,
				 ref,
                                 num:sg,
                                 pers:third),
			  restr:[]),
		    context:background:[(non_human_rel,
		  		         inst:Index)]),
	qstore:[],
	retr:[],
        arg_st:e_list).

there ---> (word,
         phon:[(a_ there)],
	 synsem:loc:(cat:head:(noun,
                               pred:minus),
                    cont:(ppro,
		          index:(there,
                                 pers:third,
                                 gen:neut),
			  restr:[]),
		    context:background:[]),
	qstore:[],
	retr:[],
        arg_st:e_list).

it ---> (word,
         phon:[(a_ it)],
	 synsem:loc:(cat:head:(noun,
                               pred:minus),
                    cont:(ppro,
		          index:(it,
                                num:sg,
                                pers:third,
                                gen:neut),
			  restr:[]),
		    context:background:[]),
	 qstore:[],
	 retr:[],
         arg_st:e_list).

him ---> (word,
          phon:[(a_ him)],
	  synsem:loc:(cat:head:(noun,
                               case:acc,
                               pred:minus),
                     cont:(ppro,
		           index:(Index,
				  ref,
                                num:sg,
                                pers:third),
			   restr:[]),
		     context:background:[(male_rel,
					  inst:Index)]),
	  qstore:[],
	  retr:[],
          arg_st:e_list).

her ---> (word,
          phon:[(a_ her)],
	  synsem:loc:(cat:head:(noun,
                               case:acc,
                               pred:minus),
                     cont:(ppro,
		           index:(Index,
				  ref,
                                num:sg,
                                pers:third),
			   restr:[]),
		     context:background:[(female_rel,
					  inst:Index)]),
	  qstore:[],
	  retr:[],
          arg_st:e_list).

you ---> (word,
          phon:[(a_ you)],
	  synsem:loc:(cat:head:(noun,
                               pred:minus),
                     cont:(ppro,
		           index:(Index,
				  ref,
                                 pers:second),
			   restr:[]),
		    context:background:[(animate_rel,
		  		         inst:Index)]),		      
	  qstore:[],
	  retr:[],
          arg_st:e_list).

they ---> (word,
           phon:[(a_ they)],
	   synsem:loc:(cat:head:(noun,
                                case:nom,
                                pred:minus),
                       cont:(ppro,
		             index:(Index,
				    ref,
                                   pers:third),
			     restr:[]),
		       context:background:[(aggregate_rel,
					    inst:Index)]),	
	   qstore:[],
	   retr:[],
           arg_st:e_list).

them ---> (word,
           phon:[(a_ them)],
	   synsem:loc:(cat:head:(noun,
                                case:acc,
                                pred:minus),
                       cont:(ppro,
		             index:(Index,
				    ref,
                                   pers:third),
			     restr:[]),
		       context:background:[(aggregate_rel,
					    inst:Index)]),	
	    qstore:[],
	    retr:[],
            arg_st:e_list).


% Count Nouns

book     ---> (word,
              phon:[(a_ book)],
	      synsem:loc:(cat:head:(noun,
                                    pred:minus),
                          cont:(npro,
			        index:(Index,
				       ref,
                                       pers:third),
				restr:[(quants:[],
					nucleus:(book_rel,
					         inst:Index))]),
			  context:background:[(non_aggregate_rel,
					       inst:Index),
					      (inanimate_rel,
					       inst:Index)]),
	      qstore:[],
	      retr:[],
              arg_st:[(loc:(cat:(head:det,
			         subcat:[])))]).

boy     ---> (word,
              phon:[(a_ boy)],
	      synsem:loc:(cat:head:(noun,
                                    pred:minus),
                          cont:(npro,
			        index:(Index,
				       ref,
                                       pers:third),
				restr:[(quants:[],
					nucleus:(boy_rel,
					         inst:Index))]),
			  context:background:[(non_aggregate_rel,
					       inst:Index),
					      (male_rel,
					       inst:Index)]),
	      qstore:[],
	      retr:[],
              arg_st:[(loc:(cat:(head:det,
			         subcat:[])))]).

faculty   ---> (word,
              phon:[(a_ faculty)],
	      synsem:loc:(cat:head:(noun,
                                    pred:minus),
                          cont:(npro,
			        index:(Index,
				       ref,
				       gen:neut,
                                       pers:third),
				restr:[(quants:[],
					nucleus:(faculty_rel,
					         inst:Index))]),
			  context:background:[(individuation_mode_rel,
					       inst:Index)]),
	      qstore:[],
	      retr:[],
              arg_st:[(loc:(cat:(head:det,
			         subcat:[])))]).

man     ---> (word,
              phon:[(a_ man)],
	      synsem:loc:(cat:head:(noun,
                                    pred:minus),
                          cont:(npro,
			        index:(Index,
				       ref,
                                       pers:third),
				restr:[(quants:[],
					nucleus:(man_rel,
					         inst:Index))]),
			  context:background:[(non_aggregate_rel,
					       inst:Index),
					      (male_rel,
					       inst:Index)]),
	      qstore:[],
	      retr:[],
              arg_st:[(loc:(cat:(head:det,
			         subcat:[])))]).

poem   --->  (word,
              phon:[(a_ poem)],
	      synsem:loc:(cat:head:(noun,
                                    pred:minus),
                          cont:(npro,
			        index:(Index,
				       ref,
                                       pers:third),
				restr:[(quants:[],
					nucleus:(poem_rel,
					         inst:Index))]),
		           context:background:[(non_aggregate_rel,
					       inst:Index),
					      (inanimate_rel,
					       inst:Index)]),	
              qstore:[],
	      retr:[],
              arg_st:[(loc:(cat:(head:det,
			         subcat:[])))]).

student ---> (word,
              phon:[(a_ student)],
	      synsem:loc:(cat:head:(noun,
                                    pred:minus),
                          cont:(npro,
			        index:(Index,
				       ref,
                                       pers:third),
				restr:[(quants:[],
					nucleus:(student_rel,
					         inst:Index))]),
			  context:background:[(non_aggregate_rel,
					       inst:Index),
					      (human_rel,
					       inst:Index)]),
	      qstore:[],
	      retr:[],
              arg_st:[(loc:(cat:(head:det,
			         subcat:[])))]).

unicorn ---> (word,
              phon:[(a_ unicorn)],
	      synsem:loc:(cat:head:(noun,
                                    pred:minus),
                          cont:(npro,
			        index:(Index,
				       ref,
                                       pers:third),
				restr:[(quants:[],
					nucleus:(unicorn_rel,
					         inst:Index))]),
			  context:background:[(non_aggregate_rel,
					       inst:Index),
					      (non_human_rel,
					       inst:Index)]),
	      qstore:[],
	      retr:[],
              arg_st:[(loc:(cat:(head:det,
			         subcat:[])))]).

woman   ---> (word,
              phon:[(a_ woman)],
	      synsem:loc:(cat:head:(noun,
                                    pred:minus),
                          cont:(npro,
			        index:(Index,
				       ref,
                                       pers:third),
				restr:[(quants:[],
					nucleus:(woman_rel,
					         inst:Index))]),
			  context:background:[(non_aggregate_rel,
					       inst:Index),
					      (female_rel,
					       inst:Index)]),
	      qstore:[],
	      retr:[],
              arg_st:[(loc:(cat:(head:det,
			         subcat:[])))]).


% DETERMINERS
% ===========

a  --->    (word,
	    phon:[(a_ a)],
	    synsem:loc:(cat:(head:(det,
				 spec:loc:(cat:(head:noun,
					       subcat:[_]
					       ),
					  cont:NounCont)
				 ),
			    marking:unmarked),
			cont:(Quant,
			      quant,
			      det:exists,
			      restind:(NounCont,
				       index:num:sg)),
			context:background:[]),
             qstore:[(Quant)],
	     retr:[],
	     arg_st:[]).

all  --->  (word,
	    phon:[(a_ all)],
	    synsem:loc:(cat:(head:(det,
				 spec:loc:(cat:(head:noun,
					       subcat:[_]
					       ),
					  cont:NounCont)
				 ),
			    marking:unmarked),
			cont:(Quant,
			      quant,
			      det:all,
			      restind:(NounCont,
				       index:num:pl)),
			context:background:[]),
             qstore:[(Quant)],
	     retr:[],
	     arg_st:[]).


every ---> (word,
	    phon:[(a_ every)],
	    synsem:loc:(cat:(head:(det,
				 spec:loc:(cat:(head:noun,
					       subcat:[_]
					       ),
					  cont:NounCont)
				 ),
			    marking:unmarked),
			cont:(Quant,
			      quant,
			      det:forall,
			      restind:(NounCont,
				       index:num:sg)),
			context:background:[]),
             qstore:[(Quant)],
	     retr:[],
	     arg_st:[]).

one   ---> (word,
	    phon:[(a_ one)],
	    synsem:loc:(cat:(head:(det,
				 spec:loc:(cat:(head:noun,
					       subcat:[_]
					       ),
					  cont:NounCont)
				 ),
			    marking:unmarked),
			cont:(Quant,
			      quant,
			      det:one,
			      restind:(NounCont,
				       index:num:sg)),
			context:background:[]),
             qstore:[(Quant)],
	     retr:[],
	     arg_st:[]).

the   ---> (word,
	    phon:[(a_ the)],
	    synsem:loc:(cat:(head:(det,
				 spec:loc:(cat:(head:noun,
					       subcat:[_]
					       ),
					  cont:NounCont)
				 ),
			    marking:unmarked),
			cont:(Quant,
			      quant,
			      det:the,
			      restind:NounCont),
			context:background:[]),
             qstore:[(Quant)],
	     retr:[],
	     arg_st:[]).

my   ---> (word,
	    phon:[(a_ my)],
	    synsem:loc:(cat:(head:(det,
				 spec:loc:(cat:(head:noun,
					       subcat:[_]
					       ),
					  cont:(index:Index1,
						restr:Restr))
				 ),
			    marking:unmarked),
			cont:(ppro,
			      index:(Index3,
			           pers:first,
			           num:sg),
			      restr:[]),         % not in P&S94, p.52
			context:background:[]),
             qstore:[(quant,
		      det:the,
		      restind:(index:Index1,
			       restr:[(poss_rel,
				       possessor:Index3,
				       possessed:Index1)|Restr]))],
	     retr:[],
	     arg_st:[]).

her   ---> (word,
	    phon:[(a_ her)],
	    synsem:loc:(cat:(head:(det,
				 spec:loc:(cat:(head:noun,
					       subcat:[_]
					       ),
					  cont:(index:Index1,
						restr:Restr))
				 ),
			    marking:unmarked),
			cont:(ppro,
			      index:(Index3,
			           pers:third,
			           num:sg),
			      restr:[]),         % not in P&S94, p.52
			context:background:[(female_rel,
					     inst:Index3)]),
             qstore:[(quant,
		      det:the,
		      restind:(index:Index1,
			       restr:[(poss_rel,
				       possessor:Index3,
				       possessed:Index1)|Restr]))],
	     retr:[],
	     arg_st:[]).

his   ---> (word,
	    phon:[(a_ his)],
	    synsem:loc:(cat:(head:(det,
				 spec:loc:(cat:(head:noun,
					       subcat:[_]
					       ),
					  cont:(index:Index1,
						restr:Restr))
				 ),
			    marking:unmarked),
			cont:(ppro,
			      index:(Index3,
			           pers:third,
			           num:sg),
			      restr:[]),         % not in P&S94, p.52
			context:background:[(male_rel,
					     inst:Index3)]),
             qstore:[(quant,
		      det:the,
		      restind:(index:Index1,
			       restr:[(poss_rel,
				       possessor:Index3,
				       possessed:Index1)|Restr]))],
	     retr:[],
	     arg_st:[]).


s   ---> (word,
	    phon:[(a_ s)],
	    synsem:loc:(cat:(head:(det,
				 spec:loc:(cat:(head:noun,
					       subcat:[_]
					       ),
					  cont:(index:Index1,
						restr:Restr))
				 ),
			    marking:unmarked),
			cont:Cont,
			context:background:[]),
             qstore:[(quant,
		      det:the,
		      restind:(index:Index1,
			       restr:[(poss_rel,
				       possessor:Index3,
				       possessed:Index1)|Restr]))],
	     retr:[],
	     arg_st:[loc:(cat:(head:noun,
			       subcat:[]),
			  cont:(Cont,
				npro,
				index:Index3))]).

some  ---> (word,
	    phon:[(a_ some)],
	    synsem:loc:(cat:(head:(det,
				 spec:loc:(cat:(head:noun,
					       subcat:[_]
					       ),
					  cont:NounCont)
				 ),
			    marking:unmarked),
			cont:(Quant,
			      quant,
			      det:exists,
			      restind:NounCont),
			context:background:[]),
             qstore:[(Quant)],
	     retr:[],
	     arg_st:[]).



% ADJECTIVES
% ==========

% intersective adjectives  (red, smart

red ---> (word,
	  phon:[(a_ red)],
	  synsem:loc:(cat:(head:(adj,
				 pred:minus,
				 mod:loc:(cat:(head:noun,
					       subcat:[_]),
					  cont:(index:Index,
						restr:Restr))),
			   subcat:[]),
		      cont:(index:Index,
			    restr:[(quants:[],
				    nucleus:(red_rel,
					     inst:Index))|Restr]),
		      context:background:[]),
	  qstore:[],
	  retr:[],
	  arg_st:[]).


smart ---> (word,
	  phon:[(a_ smart)],
	  synsem:loc:(cat:(head:(adj,
				 pred:minus,
				 mod:loc:(cat:(head:noun,
					       subcat:[_]),
					  cont:(index:Index,
						restr:Restr))),
			   subcat:[]),
		      cont:(index:Index,
			    restr:[(quants:[],
				    nucleus:(smart_rel,
					     inst:Index))|Restr]),
		      context:background:[]),
	  qstore:[],
	  retr:[],
	  arg_st:[]).

smart ---> (word,
	  phon:[(a_ smart)],
	  synsem:loc:(cat:(head:(adj,
				 pred:plus,
				 mod:none)),
		      cont:(quants:[],
			    nucleus:(be_smart_rel,
			             smart:Index)),
		      context:background:[]),
	  qstore:[],
	  retr:[],
	  arg_st:[(loc:(cat:(head:noun,
	                     subcat:[]),
			cont:index:Index))]).


% operator adjectives  (alleged, former)

% mod:loc:cont:restr: only one element allowed to make sure this is
% a psoa as necessary for soa_arg value; problem acknowledged in
% P&S94, p.330f, no solution suggested (see Kasper 1996)

alleged ---> (word,
	  phon:[(a_ alleged)],
	  synsem:loc:(cat:(head:(adj,
				 mod:loc:(cat:(head:noun,
					       subcat:[_]),
					  cont:(index:Index,
						restr:[Restr]))),
			   subcat:[]),
		      cont:(index:Index,
			    restr:[(quants:[],
				    nucleus:(alleged_rel,
					     soa_arg:Restr))]),
		      context:background:[]),
	  qstore:[],
	  retr:[],
	  arg_st:[]). 



% VERBS
% =====

approach --->  (word,
            phon:[(a_ approach)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(approach_rel,
                                       approacher:Index))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index))]).

approaches --->  (word,
            phon:[(a_ approaches)],
	    synsem:loc:(cat:(head:(verb,
                                 vform:fin,
                                 pred:plus,
                                 aux:minus),
                             subcat:[(loc:cont:index:(pers:third,
                                                      num:sg))]),
                        cont:(quants:[],
			      nucleus:(approach_rel,
                                      approacher:Index))),
            qstore:[],
            retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index))]).

go   --->  (word,
            phon:[(a_ go)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(go_rel,
                                      goer:Index))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index))]).


goes   --->  (word,
            phon:[(a_ goes)],
	    synsem:loc:(cat:head:(verb,
                                 vform: fin,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(go_rel,
                                      goer:Index))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index))]).


leave --->  (word,
            phon:[(a_ leave)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(leave_rel,
                                      leaver:Index))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index))]).

leaves --->  (word,
            phon:[(a_ leaves)],
	    synsem:loc:(cat:(head:(verb,
                                 vform:fin,
                                 pred:plus,
                                 aux:minus),
                             subcat:[(loc:cont:index:(pers:third,
                                                      num:sg))]),
                        cont:(quants:[],
			      nucleus:(leave_rel,
                                      leaver:Index))),
            qstore:[],
            retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index))]).

run  --->  (word,
            phon:[(a_ run)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(run_rel,
                                       runner:Index))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index))]).

runs  --->  (word,
            phon:[(a_ runs)],
	    synsem:loc:(cat:(head:(verb,
                                 vform:fin,
                                 pred:plus,
                                 aux:minus),
                             subcat:[(loc:cont:index:(pers:third,
                                                      num:sg))]),
                        cont:(quants:[],
			      nucleus:(run_rel,
                                       runner:Index))),
            qstore:[],
            retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index))]).


walk --->  (word,
            phon:[(a_ walk)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(walk_rel,
                                      walker:Index))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index))]).

walks --->  (word,
            phon:[(a_ walks)],
	    synsem:loc:(cat:(head:(verb,
                                 vform:fin,
                                 pred:plus,
                                 aux:minus),
                             subcat:[(loc:cont:index:(pers:third,
                                                      num:sg))]),
                        cont:(quants:[],
			      nucleus:(walk_rel,
                                      walker:Index))),
            qstore:[],
            retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index))]).


rain --->  (word,
            phon:[(a_ rain)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:rain_rel)),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:it))]).

rains --->  (word,
            phon:[(a_ rains)],
	    synsem:loc:(cat:(head:(verb,
                                  vform:fin,
                                  pred:plus,
                                  aux:minus),
                             subcat:[(loc:cont:index:(pers:third,
                                                           num:sg))]),
                        cont:(quants:[],
			      nucleus:rain_rel)),
            qstore:[],
            retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:it))]).


know --->  (word,
            phon:[(a_ know)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(know_rel,
                                      knower:Index1,
                                      known:Index2))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                          cont:index:Index2))]).

knows --->  (word,
             phon:[(a_ knows)],
	     synsem:loc:(cat:(head:(verb,
                                   vform: fin,
                                   pred: plus,
                                   aux: minus),
                              subcat:[(loc:cont:(psoa;index:(pers:third,
                                                              num:sg)))|_]),
                        cont:(quants:[],
			      nucleus:(know_rel,
                                      knower:Index1,
                                      known:Index2))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                          cont:index:Index2))]).



like --->  (word,
            phon:[(a_ like)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(like_rel,
                                      liker:Index1,
                                      liked:Index2))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                          cont:index:Index2))]).

likes --->  (word,
             phon:[(a_ likes)],
	     synsem:loc:(cat:(head:(verb,
                                   vform: fin,
                                   pred: plus,
                                   aux: minus),
                              subcat:[(loc:cont:(psoa;index:(pers:third,
                                                              num:sg)))|_]),
                        cont:(quants:[],
			      nucleus:(like_rel,
                                      liker:Index1,
                                      liked:Index2))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                          cont:index:Index2))]).

love --->  (word,
            phon:[(a_ love)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(love_rel,
                                      lover:Index1,
                                      loved:Index2))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                          cont:index:Index2))]).

loves --->  (word,
             phon:[(a_ loves)],
	     synsem:loc:(cat:(head:(verb,
                                   vform: fin,
                                   pred: plus,
                                   aux: minus),
                              subcat:[(loc:cont:(psoa;index:(pers:third,
                                                              num:sg)))|_]),
                        cont:(quants:[],
			      nucleus:(love_rel,
                                      lover:Index1,
                                      loved:Index2))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                          cont:index:Index2))]).

own --->  (word,
            phon:[(a_ own)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(own_rel,
                                      owner:Index1,
                                      owned:Index2))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                          cont:index:Index2))]).

owns --->  (word,
             phon:[(a_ owns)],
	     synsem:loc:(cat:(head:(verb,
                                   vform: fin,
                                   pred: plus,
                                   aux: minus),
                              subcat:[(loc:cont:(psoa;index:(pers:third,
                                                              num:sg)))|_]),
                        cont:(quants:[],
			      nucleus:(own_rel,
                                      owner:Index1,
                                      owned:Index2))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                          cont:index:Index2))]).

see  --->  (word,
            phon:[(a_ see)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(see_rel,
                                      seer:Index1,
                                      seen:Index2))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                          cont:index:Index2))]).

sees  --->  (word,
             phon:[(a_ sees)],
	     synsem:loc:(cat:(head:(verb,
                                   vform: fin,
                                   pred: plus,
                                   aux: minus),
                              subcat:[(loc:cont:(psoa;index:(pers:third,
                                                              num:sg)))|_]),
                        cont:(quants:[],
			      nucleus:(see_rel,
                                      seer:Index1,
                                      seen:Index2))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                          cont:index:Index2))]).


demand --->  (word,
            phon:[(a_ demand)],
	    synsem:loc:(cat:(head:(verb,
                                  vform:base,
                                  pred:plus,
                                  aux:minus)),
                        cont:(quants:[],
			      nucleus:(demand_rel,
                                       demander:Index,
                                       demanded:Psoa))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index)),
                     (loc:(cat:(head:vform:base,
                                marking:that,
                                subcat:[]),
                           cont:Psoa))]).


demands --->  (word,
            phon:[(a_ demands)],
	    synsem:loc:(cat:(head:(verb,
                                  vform:fin,
                                  pred:plus,
                                  aux:minus),
                             subcat:[(loc:cont:(psoa;index:(pers:third,
                                                            num:sg)))|_]),
                        cont:(quants:[],
			      nucleus:(demand_rel,
                                       demander:Index,
                                       demanded:Psoa))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index)),
                     (loc:(cat:(head:vform:base,
                                marking:that,
                                subcat:[]),
                           cont:Psoa))]).



require --->  (word,
            phon:[(a_ require)],
	    synsem:loc:(cat:(head:(verb,
                                  vform:base,
                                  pred:plus,
                                  aux:minus)),
                        cont:(quants:[],
			      nucleus:(require_rel,
                                       reqer:Index,
                                       reqed:Psoa))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index)),
                     (loc:(cat:(head:vform:base,
                                marking:that,
                                subcat:[]),
                           cont:Psoa))]).


requires --->  (word,
            phon:[(a_ requires)],
	    synsem:loc:(cat:(head:(verb,
                                  vform:fin,
                                  pred:plus,
                                  aux:minus),
                             subcat:[(loc:cont:(psoa;index:(pers:third,
                                                            num:sg)))|_]),
                        cont:(quants:[],
			      nucleus:(require_rel,
                                       reqer:Index,
                                       reqed:Psoa))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index)),
                     (loc:(cat:(head:vform:base,
                                marking:that,
                                subcat:[]),
                           cont:Psoa))]).


say --->  (word,
           phon:[(a_ say)],
	   synsem:loc:(cat:head:(verb,
                                vform:base,
                                pred:plus,
                                aux:minus),
                       cont:(quants:[],
		             nucleus:(say_rel,
                                     sayer:Index,
                                     said:Psoa))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index)),
                     (loc:(cat:(head:vform:fin,
                                marking:that,
                                subcat:[]),
                            cont:Psoa))]).

says --->  (word,
            phon:[(a_ says)],
	    synsem:loc:(cat:(head:(verb,
                                  vform: fin,
                                  pred: plus,
                                  aux: minus),
                             subcat:[(loc:cont:(psoa;index:(pers:third,
                                                            num:sg)))|_]),
                        cont:(quants:[],
			      nucleus:(say_rel,
                                      sayer:Index,
                                      said:Psoa))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index)),
                     (loc:(cat:(head:vform:fin,
                                marking:(that;unmarked),
                                subcat:[]),
                           cont:Psoa))]).

think --->  (word,
           phon:[(a_ think)],
	   synsem:loc:(cat:head:(verb,
                                vform:base,
                                pred:plus,
                                aux:minus),
                       cont:(quants:[],
		             nucleus:(think_rel,
                                     thinker:Index,
                                     thought:Psoa))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index)),
                     (loc:(cat:(head:vform:fin,
                                marking:that,
                                subcat:[]),
                            cont:Psoa))]).

thinks --->  (word,
            phon:[(a_ thinks)],
	    synsem:loc:(cat:(head:(verb,
                                  vform: fin,
                                  pred: plus,
                                  aux: minus),
                             subcat:[(loc:cont:(psoa;index:(pers:third,
                                                            num:sg)))|_]),
                        cont:(quants:[],
			      nucleus:(think_rel,
                                      thinker:Index,
                                      thought:Psoa))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index)),
                     (loc:(cat:(head:vform:fin,
                                marking:(that;unmarked),
                                subcat:[]),
                           cont:Psoa))]).


give --->  (word,
            phon:[(a_ give)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(give_rel,
                                      giver:Index1,
                                      gift:Index2,
                                      givee:Index3))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                           cont:index:Index2)),
                     (loc:(cat:(head:(prep,
                                      pform:to),
                                subcat:[]),
                           cont:index:Index3))]).


give --->  (word,
            phon:[(a_ give)],
	    synsem:loc:(cat:head:(verb,
                                 vform: base,
                                 pred: plus,
                                 aux: minus),
                        cont:(quants:[],
			      nucleus:(give_rel,
                                      giver:Index1,
                                      gift:Index2,
                                      givee:Index3))),
	    qstore:[],
	    retr:[],
            arg_st:[(loc:(cat:(head:noun,
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
                                      case:acc),
                                subcat:[]),
                           cont:index:Index3)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                           cont:index:Index2))]).


gives --->  (word,
             phon:[(a_ gives)],
	     synsem:loc:(cat:(head:(verb,
                                   vform:fin,
                                   pred:plus,
                                   aux:minus),
                                   subcat:[(loc:cont:(psoa;index:(pers:third,
                                                                   num:sg)))|_]),
                        cont:(quants:[],
			      nucleus:(give_rel,
                                      giver:Index1,
                                      gift:Index2,
                                      givee:Index3))),
            qstore:[],
            retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                          cont:index:Index2)),
                     (loc:(cat:(head:(prep,
                                      pform:to),
                                subcat:[]),
                          cont:index:Index3))]).

gives --->  (word,
             phon:[(a_ gives)],
	     synsem:loc:(cat:(head:(verb,
                                   vform:fin,
                                   pred:plus,
                                   aux:minus),
                                   subcat:[(loc:cont:(psoa;index:(pers:third,
                                                                   num:sg)))|_]),
                        cont:(quants:[],
			      nucleus:(give_rel,
                                      giver:Index1,
                                      gift:Index2,
                                      givee:Index3))),
            qstore:[],
            retr:[],
            arg_st:[(loc:(cat:(head:(noun,
				     case:nom),
                               subcat:[]),
                          cont:index:Index1)),
                     (loc:(cat:(head:(noun,
                                      case:acc),
                                subcat:[]),
                           cont:index:Index3)),
                     (loc:(cat:(head:(noun,
				      case:acc),
                                subcat:[]),
                           cont:index:Index2))]).

%%% Raising VERBS
%   =============

seem  ---> (word,
           phon:[(a_ seem)],
	   synsem:loc:(cat:head:(verb,
                                vform:base,
                                pred:plus,
                                aux:minus),
                      cont:(quants:[],
		            nucleus:(seem_rel,
                                    soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(Synsem),
	      (loc:(cat:(head:(verb,
                               vform:inf),
                         subcat:[(Synsem)]),
                         cont:Cont))]).

seems ---> (word,
           phon:[(a_ seems)],
	   synsem:loc:(cat:head:(verb,
                                vform:fin,
                                pred:plus,
                                aux:minus),
                      cont:(quants:[],
		            nucleus:(seem_rel,
                                     soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(Synsem,
	       loc:(cat:head:case:nom,
	            cont:index:(num:sg,
			       pers:third))),
	      (loc:(cat:(head:(verb,
                               vform:inf),
                         subcat:[(Synsem)]),
                         cont:Cont))]).


tend  ---> (word,
           phon:[(a_ tend)],
	   synsem:loc:(cat:head:(verb,
                                vform:base,
                                pred:plus,
                                aux:minus),
                      cont:(quants:[],
		            nucleus:(tend_rel,
                                    soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(Synsem),
	      (loc:(cat:(head:(verb,
                               vform:inf),
                         subcat:[(Synsem)]),
                         cont:Cont))]).

tends ---> (word,
           phon:[(a_ tends)],
	   synsem:loc:(cat:head:(verb,
                                vform:fin,
                                pred:plus,
                                aux:minus),
                      cont:(quants:[],
		            nucleus:(tend_rel,
                                     soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(Synsem,
	       loc:(cat:head:case:nom,
	            cont:index:(num:sg,
			       pers:third))),
	      (loc:(cat:(head:(verb,
                               vform:inf),
                         subcat:[(Synsem)]),
                         cont:Cont))]).

% Object Raising: believe, expect

believe  ---> (word,
           phon:[(a_ believe)],
	   synsem:loc:(cat:head:(verb,
                                vform:base,
                                pred:plus,
                                aux:minus),
                      cont:(quants:[],
		            nucleus:(believe_rel,
				     believer:(Index),
                                     soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(loc:(cat:(head:noun,
			subcat:e_list),
	            cont:index:Index)),
	      (Synsem,loc:cat:head:case:acc),
	      (loc:(cat:(head:(verb,
                               vform:inf),
                         subcat:[(Synsem)]),
                         cont:Cont))]).

believes ---> (word,
           phon:[(a_ believes)],
	   synsem:loc:(cat:head:(verb,
                                vform:fin,
                                pred:plus,
                                aux:minus),
                      cont:(quants:[],
		            nucleus:(believe_rel,
				     believer:(Index),
                                     soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(loc:(cat:(head:(noun,
			       case:nom),
			subcat:e_list),
	            cont:index:(Index,
				num:sg,
				pers:third))),
	      (Synsem,
	       loc:cat:head:case:acc),
	      (loc:(cat:(head:(verb,
                               vform:inf),
                         subcat:[(Synsem)]),
                         cont:Cont))]).

expect  ---> (word,
           phon:[(a_ expect)],
	   synsem:loc:(cat:head:(verb,
                                vform:base,
                                pred:plus,
                                aux:minus),
                      cont:(quants:[],
		            nucleus:(expect_rel,
				     expecter:(Index),
                                     soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(loc:(cat:(head:noun,
			subcat:e_list),
	            cont:index:Index)),
	      (Synsem,loc:cat:head:case:acc),
	      (loc:(cat:(head:(verb,
                               vform:inf),
                         subcat:[(Synsem)]),
                         cont:Cont))]).

expects ---> (word,
           phon:[(a_ expects)],
	   synsem:loc:(cat:head:(verb,
                                vform:fin,
                                pred:plus,
                                aux:minus),
                      cont:(quants:[],
		            nucleus:(expect_rel,
				     expecter:(Index),
                                     soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(loc:(cat:(head:(noun,
			       case:nom),
			subcat:e_list),
	            cont:index:(Index,
				num:sg,
				pers:third))),
	      (Synsem,
	       loc:cat:head:case:acc),
	      (loc:(cat:(head:(verb,
                               vform:inf),
                         subcat:[(Synsem)]),
                         cont:Cont))]).



%%% Control VERBS
%   =============

try  ---> (word,
           phon:[(a_ try)],
	   synsem:loc:(cat:head:(verb,
                                vform:base,
                                pred:plus,
                                aux:minus),
                      cont:(quants:[],
		            nucleus:(try_rel,
				     tryer:(ref,
					    Index),
                                    soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(loc:cont:index:Index),
	      (loc:(cat:(head:(verb,
                               vform:inf),
                         subcat:[(loc:cont:index:Index)]),
                         cont:Cont))]).

tries ---> (word,
           phon:[(a_ tries)],
	   synsem:loc:(cat:head:(verb,
                                vform:fin,
                                pred:plus,
                                aux:minus),
                      cont:(quants:[],
		            nucleus:(try_rel,
				     tryer:(ref,
					    Index,
					    num:sg,
					    pers:third),
                                     soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(loc:(cat:head:case:nom,
	            cont:index:Index)),
	      (loc:(cat:(head:(verb,
                               vform:inf),
                         subcat:[(loc:cont:index:Index)]),
                         cont:Cont))]).

% Object Control: persuade

persuade  ---> (word,
           phon:[(a_ persuade)],
	   synsem:loc:(cat:head:(verb,
                                vform:base,
                                pred:plus,
                                aux:minus),
                      cont:(quants:[],
		            nucleus:(persuade_rel,
				     persuader:(ref,
					    Index1),
				     persuadee:Index2,
                                    soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(loc:(cat:(head:noun,
			 subcat:e_list),
		    cont:index:Index1)),
	      (loc:(cat:(head:(noun,
			       case:acc),
			 subcat:e_list),
		    cont:index:Index2)),
	      (loc:(cat:(head:(verb,
                               vform:inf),
                         subcat:[(loc:(cat:(head:noun,
					    subcat:e_list),
				       cont:index:Index2))]),
                         cont:Cont))]).

persuades ---> (word,
           phon:[(a_ persuades)],
	   synsem:loc:(cat:head:(verb,
                                vform:fin,
                                pred:plus,
                                aux:minus),
                      cont:(quants:[],
		            nucleus:(persuade_rel,
				     persuader:(ref,
					    Index1,
					    num:sg,
					    pers:third),
				     persuadee:Index2,
                                     soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(loc:(cat:(head:case:nom,
			 subcat:e_list),
	            cont:index:Index1)),
	      (loc:(cat:(head:(noun,
			       case:acc),
			 subcat:e_list),
		    cont:index:Index2)),
	      (loc:(cat:(head:(verb,
                               vform:inf),
                         subcat:[(loc:(cat:(head:noun,
					    subcat:e_list),
				       cont:index:Index2))]),
                         cont:Cont))]).


%%% AUXILIARIES
%   ===========

be  --->  (word,
           phon:[(a_ be)],
	   synsem:loc:(cat:head:(verb,
                                vform:base,
                                pred:plus,
				inv:minus,
                                aux:plus),
                      cont:Cont),
	   qstore:[],
	   retr:[],
      arg_st:[(Synsem),(loc:(cat:(head:((adj;noun),
                                        pred:plus),
                                  subcat:[(Synsem)]),
                                  cont:Cont))]).

is  --->  (word,
           phon:[(a_ is)],
	   synsem:loc:(cat:head:(verb,
                                vform:fin,
                                pred:plus,
                                aux:plus),
                      cont:Cont),
	   qstore:[],
	   retr:[],
      arg_st:[(Synsem,
	       loc:cont:index:(pers:third,
			       num:sg)),
	      (loc:(cat:(head:((adj;noun),
                                  pred:plus),
                                  subcat:[(Synsem)]),
                                  cont:Cont))]).

are --->  (word,
           phon:[(a_ are)],
	   synsem:loc:(cat:head:(verb,
                                vform:fin,
                                pred:plus,
                                aux:plus),
                      cont:Cont),
	   qstore:[],
	   retr:[],
      arg_st:[(Synsem,
	       loc:cont:index:(pers:third,
			       num:pl)),
	      (loc:(cat:(head:((adj;noun),
                                        pred:plus),
                                  subcat:[(Synsem)]),
                                  cont:Cont))]).


can  ---> (word,
           phon:[(a_ can)],
	   synsem:loc:(cat:head:(verb,
                                vform:fin,
                                pred:plus,
                                aux:plus),
                      cont:(quants:[],
		            nucleus:(modal_rel,
                                    soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(Synsem),(loc:(cat:(head:(verb,
                                        vform:base),
                                  subcat:[(Synsem)]),
                                  cont:Cont))]).


could ---> (word,
           phon:[(a_ could)],
	   synsem:loc:(cat:head:(verb,
                                vform:fin,
                                pred:plus,
                                aux:plus),
                      cont:(quants:[],
		            nucleus:(modal_rel,
                                    soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(Synsem),(loc:(cat:(head:(verb,
                                        vform:base),
                                  subcat:[(Synsem)]),
                                  cont:Cont))]).


does  ---> (word,
           phon:[(a_ does)],
	   synsem:loc:(cat:head:(verb,
                                vform:fin,
                                pred:plus,
                                aux:plus),
                      cont:Cont),
	   qstore:[],
	   retr:[],
      arg_st:[(Synsem,
	       loc:cont:index:(pers:third,
			       num:sg)),
	      (loc:(cat:(head:(verb,
                               vform:base),
                         subcat:[(Synsem)]),
                         cont:Cont))]).


will ---> (word,
           phon:[(a_ will)],
	   synsem:loc:(cat:head:(verb,
                                vform:fin,
                                pred:plus,
                                aux:plus),
                      cont:(quants:[],
		            nucleus:(future_rel,
                                    soa_arg:Cont))),
	   qstore:[],
	   retr:[],
      arg_st:[(Synsem),(loc:(cat:(head:(verb,
                                        vform:base),
                                  subcat:[(Synsem)]),
                                  cont:Cont))]).

to --->   (word,
	   phon:[(a_ to)],
	   synsem:loc:(cat:head:(verb,
				 vform:inf,
				 aux:plus,
				 inv:minus,
				 pred:plus),
		       cont:Cont
		       ),
	   qstore:[],
	   retr:[],
	   arg_st:[(Subj),(loc:(cat:(head:(verb,
					   vform:base
					   ),
				     subcat:[Subj]),
				cont:Cont))]).


% PREPOSITIONS
% ============

to ---> (word,
         phon:[(a_ to)],
	 synsem:loc:(cat:head:(prep,
                              pform:to),
		     context:background:[]),
	 arg_st:[loc:cat:head:case:acc]).



% COMPLEMENTIZERS
% ===============

that ---> (word,
           phon:[(a_ that)],
	   synsem:loc:(cat:(head:(mark,
                                  spec:(loc:(cat:(head:(verb,
                                                        vform:(fin;base)),
						  marking:unmarked,
                                                  subcat:[]),
                                              cont:Cont))),
                            marking:that),
                       cont:Cont,
		       context:background:[]),
          arg_st:[],
	  qstore:[],
	  retr:[]).


%====================================================================